### ISSUE TITLE
Upgraded major `pyjwt==2.3.0` led to issues

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos#159]
It turns out pyjwt 2.3.0 has changed some of the exported values it used to provide, and the authentication didn't work out of the box, as we currently, so it needs to be adapted accordingly, mapping for a future opportunity

```
❯ http http://127.0.0.1:8181/api/kytos/core/auth/users
HTTP/1.0 500 INTERNAL SERVER ERROR
Access-Control-Allow-Origin: *
Content-Length: 215
Content-Type: application/json
Date: Wed, 12 Jan 2022 03:28:49 GMT
Server: Werkzeug/2.0.2 Python/3.9.4

{
    "code": 500,
    "description": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
    "name": "Internal Server Error"
}
```

```
Traceback (most recent call last):
  File "/home/viniarck/repos/kytos/kytos/core/auth.py", line 29, in wrapper
    raise ValueError("The attribute 'content' has an invalid "
ValueError: The attribute 'content' has an invalid value 'None'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.4/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.4/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.4/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.4/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.4/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/viniarck/repos/kytos/kytos/core/auth.py", line 36, in wrapper
    jwt.ExpiredSignature,
AttributeError: module 'jwt' has no attribute 'ExpiredSignature'
kytos $>
```

**Comment by viniarck** [comment]
Landed on #284
