### ISSUE TITLE
InterfaceID isn't pickleable anymore

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos#251]
@italovalcy has reported this unexpected regression that showed up when `storehouse` tried to pickle load a stored `UNI` that keeps reference of and `Interface` and its id:

```
2022-07-20 18:15:06,643 - ERROR [kytos.core.helpers] [helpers.py:151:handler_context_apm] (thread_pool_db_1) listen_to handler: <function Main.event_update at 0x7f486c2225e0>, args: (<Ma
in(storehouse, stopped 139948313257536)>, KytosEvent('kytos.storehouse.update', {'namespace': 'kytos.mef_eline.circuits', 'box_id': 'fd53c1c0aeb843ecb31b66fa6a835a24', 'data': {'795a7e31
04074e': {'id': '795a7e3104074e', 'name': 'epl', 'uni_a': {'interface_id': '00:00:00:00:00:00:00:01:1', 'tag': None}, 'uni_z': {'interface_id': '00:00:00:00:00:00:00:03:1', 'tag': None},
 'start_date': '2022-07-20T21:15:06', 'end_date': None, 'queue_id': None, 'bandwidth': 0, 'primary_links': [], 'backup_links': [], 'current_path': [], 'primary_path': [], 'backup_path':
[], 'dynamic_backup_path': True, 'metadata': {}, 'request_time': '2022-07-20T21:15:06', 'creation_time': '2022-07-20T21:15:06', 'owner': None, 'circuit_scheduler': [], 'active': False, '
enabled': True, 'archived': False, 'priority': 100}}, 'callback': <bound method StoreHouse._save_evc_callback of <napps.kytos.mef_eline.storehouse.StoreHouse object at 0x7f48641f2550>>},
 0)) traceback: Traceback (most recent call last):,   File "/home/viniarck/repos/kytos/kytos/core/helpers.py", line 146, in handler_context_apm,     result = handler(*args),   File "/hom
e/viniarck/repos/napps/napps/kytos/storehouse/main.py", line 320, in event_update,     box = self.backend.retrieve(namespace, box_id),   File "/home/viniarck/repos/napps/napps/kytos/stor
ehouse/backends/fs.py", line 115, in retrieve,     return self._load_from_file(destination),   File "/home/viniarck/repos/napps/napps/kytos/storehouse/backends/fs.py", line 83, in _load_
from_file,     data = pickle.load(load_file), TypeError: __new__() missing 1 required positional argument: 'port',
``` 

It seems that the impact is only related to pickle. Reading from the official docs, https://docs.python.org/3.9/library/pickle.html#pickling-class-instances, indeed pickle calls `__new__` again, so it could be can again, see this example:

```
kytos $> type(controller.switches[sw1].interfaces[1].as_dict()['id'])
Out[11]: kytos.core.id.InterfaceID

kytos $> import pickle

kytos $> pickle.dumps(d)
Out[13]: b'\x80\x04\x95#\x01\x00\x00\x00\x00\x00\x00}\x94(\x8c\x02id\x94\x8c\rkytos.core.id\x94\x8c\x0bInterfaceID\x94\x93\x94\x8c\x1900:00:00:00:00:00:00:01:1\x94\x85\x94\x81\x94N}\x94(
\x8c\x06switch\x94\x8c\x1700:00:00:00:00:00:00:01\x94\x8c\x04port\x94K\x01u\x86\x94b\x8c\x04name\x94\x8c\x07s1-eth1\x94\x8c\x0bport_number\x94K\x01\x8c\x03mac\x94\x8c\x1156:24:30:8f:d9:9
6\x94h\th\n\x8c\x04type\x94\x8c\tinterface\x94\x8c\x03nni\x94\x89\x8c\x03uni\x94\x88\x8c\x05speed\x94GA\xd2\xa0_ \x00\x00\x00\x8c\x08metadata\x94}\x94\x8c\x04lldp\x94\x88\x8c\x06active\x
94\x88\x8c\x07enabled\x94\x88\x8c\x04link\x94\x8c\x00\x94u.'

kytos $> pickled = pickle.dumps(d)

kytos $> pickle.loads(pickled)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/repos/kytos/kytos/core/kytosd.py in <module>
----> 1 pickle.loads(pickled)

TypeError: __new__() missing 1 required positional argument: 'port'

```  

Potential solutions:

- Probably the safest and the one with least refactoring would be to cast again the type into a `str` and then the new introduced types `InterfaceID` and `LinkID` are used only when building the formatted str. 
- We could also try to parse the `__repr__` representation, but for `LinkID` that wouldn't be applicable since it uses a md5 digest

**Comment by viniarck** [comment]
Also, another good news is that storehouse is also being deprecated and its the only place that pickle is being so far
