### ISSUE TITLE
APIServer gets shutdown before NApps stop handling their endpoints

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos#282]
Currently, the APIServer instance is getting shutdown before NApps are unloaded when stopping the controller. 

I found this when I was fixing issue #155. This can make the graceful shutdown harder since a NApp might still be executing and making requests to another NApp endpoint that hasn't been shutdown yet, so instead of a 404 it'll get a connection error, **NApps are supposed to handle all of these errors**, but some kytos-ng NApps aren't yet, so to make it more graceful making sure the platform does it best to perform a graceful shutdown, the APIServer should be stopped after NApps get unloaded, similar to TCP KytosServer instance. This only impacts when kytosd gets shutdown and NApps aren't handling IO errors completely.

Here's an example when `mef_eline` still has HTTP requests on its main `execute` Thread going on and the APIServer gets shutdown and a call to `/api/amlight/sdntrace_cp/trace` results in connection error:

```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8181): Max retries exceeded with url: /api/amlight/sdntrace_cp/trace (Caused by NewConnectionError('<urllib3.
connection.HTTPConnection object at 0x7f1fed997730>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-09-07 19:09:48,318 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/flow_manager/v2/flows - OPTIONS,DELETE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
2022-09-07 19:09:48,319 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/flow_manager/v2/flows - OPTIONS,HEAD,GET
2022-09-07 19:09:48,319 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/flow_manager/v2/stored_flows/<dpid> - OPTIONS,HEAD,GET
    self.run()
  File "/home/viniarck/repos/kytos/kytos/core/napps/base.py", line 250, in run
2022-09-07 19:09:48,319 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/flow_manager/v2/delete/<dpid> - OPTIONS,POST
2022-09-07 19:09:48,319 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/flow_manager/v2/flows/<dpid> - OPTIONS,POST
    self.execute()
2022-09-07 19:09:48,319 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/flow_manager/v2/flows/<dpid> - OPTIONS,DELETE
  File "/home/viniarck/repos/napps/napps/kytos/mef_eline/main.py", line 77, in execute
2022-09-07 19:09:48,319 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/flow_manager/v2/flows/<dpid> - OPTIONS,HEAD,GET
2022-09-07 19:09:48,319 - INFO [kytos.core.api_server] (MainThread) The Rest endpoints from /api/kytos/flow_manager/ were disabled.
    self.execute_consistency()
  File "/home/viniarck/repos/napps/napps/kytos/mef_eline/main.py", line 91, in execute_consistency
2022-09-07 19:09:48,320 - INFO [kytos.core.controller] (MainThread) Shutting down NApp amlight/flow_stats...
2022-09-07 19:09:48,320 - INFO [kytos.core.api_server] (MainThread) Stopped /api/amlight/flow_stats/packet_count/per_flow/<dpid> - OPTIONS,HEAD,GET
    if circuit.check_traces():
  File "/home/viniarck/repos/napps/napps/kytos/mef_eline/models/evc.py", line 998, in check_traces
2022-09-07 19:09:48,320 - INFO [kytos.core.api_server] (MainThread) Stopped /api/amlight/flow_stats/packet_count/sum/<dpid> - OPTIONS,HEAD,GET
2022-09-07 19:09:48,320 - INFO [kytos.core.api_server] (MainThread) Stopped /api/amlight/flow_stats/bytes_count/per_flow/<dpid> - OPTIONS,HEAD,GET
    trace_a = self.run_sdntrace(self.uni_a)
2022-09-07 19:09:48,320 - INFO [kytos.core.api_server] (MainThread) Stopped /api/amlight/flow_stats/bytes_count/sum/<dpid> - OPTIONS,HEAD,GET
  File "/home/viniarck/repos/napps/napps/kytos/mef_eline/models/evc.py", line 990, in run_sdntrace
2022-09-07 19:09:48,321 - INFO [kytos.core.api_server] (MainThread) Stopped /api/amlight/flow_stats/flow/match/<dpid> - OPTIONS,HEAD,GET
2022-09-07 19:09:48,321 - INFO [kytos.core.api_server] (MainThread) Stopped /api/amlight/flow_stats/flow/stats/<dpid> - OPTIONS,HEAD,GET
    response = requests.put(endpoint, json=data_uni)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.12/lib/python3.9/site-packages/requests/api.py", line 132, in put
2022-09-07 19:09:48,321 - INFO [kytos.core.api_server] (MainThread) Stopped /api/amlight/flow_stats/packet_count/<flow_id> - OPTIONS,HEAD,GET
2022-09-07 19:09:48,321 - INFO [kytos.core.api_server] (MainThread) Stopped /api/amlight/flow_stats/bytes_count/<flow_id> - OPTIONS,HEAD,GET
2022-09-07 19:09:48,321 - INFO [kytos.core.api_server] (MainThread) The Rest endpoints from /api/amlight/flow_stats/ were disabled.
    return request('put', url, data=data, **kwargs)
2022-09-07 19:09:48,321 - INFO [kytos.core.controller] (MainThread) Shutting down NApp kytos/mef_eline...
2022-09-07 19:09:48,322 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/schedule/ - OPTIONS,POST
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.12/lib/python3.9/site-packages/requests/api.py", line 61, in request
2022-09-07 19:09:48,325 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/schedule - OPTIONS,HEAD,GET
2022-09-07 19:09:48,325 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/ - OPTIONS,POST
    return session.request(method=method, url=url, **kwargs)
2022-09-07 19:09:48,325 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/ - OPTIONS,HEAD,GET
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.12/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
2022-09-07 19:09:48,326 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/schedule/<schedule_id> - OPTIONS,DELETE
    resp = self.send(prep, **send_kwargs)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.12/lib/python3.9/site-packages/elasticapm/instrumentation/packages/base.py", line 205, in call_if_sampling
2022-09-07 19:09:48,326 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/schedule/<schedule_id> - OPTIONS,PATCH
2022-09-07 19:09:48,326 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/<circuit_id>/metadata/<key> - OPTIONS,DELETE
    return wrapped(*args, **kwargs)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.12/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
2022-09-07 19:09:48,326 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/<circuit_id>/metadata - OPTIONS,POST
    r = adapter.send(request, **kwargs)
2022-09-07 19:09:48,326 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/<circuit_id>/metadata - OPTIONS,HEAD,GET
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.12/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
2022-09-07 19:09:48,326 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/<circuit_id>/redeploy - OPTIONS,PATCH
2022-09-07 19:09:48,327 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/<circuit_id> - OPTIONS,DELETE
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8181): Max retries exceeded with url: /api/amlight/sdntrace_cp/trace (Caused by NewConnectionError('<urlli
b3.connection.HTTPConnection object at 0x7f1fed997730>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-09-07 19:09:48,327 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/<circuit_id> - OPTIONS,HEAD,GET
2022-09-07 19:09:48,327 - INFO [kytos.core.api_server] (MainThread) Stopped /api/kytos/mef_eline/v2/evc/<circuit_id> - OPTIONS,PATCH
2022-09-07 19:09:48,327 - INFO [kytos.core.api_server] (MainThread) The Rest endpoints from /api/kytos/mef_eline/ were disabled.
```

**Comment by viniarck** [comment]
Landed on #284
