### ISSUE TITLE
`GET /api/kytos/core/auth/login` can result in internal error 500

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos#298]
The request handler `GET /api/kytos/core/auth/login` is assuming that the `Authorization` header will always be set, which isn't true, if a client makes a mistake of not setting it then it could result in HTTP 500, for instance:

### How to reproduce

- Start `kytosd -f --database mongodb`  
- Send this request `GET /api/kytos/core/auth/login` without an Authorization header:
```
curl http://127.0.0.1:8181/api/kytos/core/auth/login

{"code":500,"description":"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.","na
me":"Internal Server Error"}

``` 
- Notice a traceback and this 500 as a result:
```
2022-10-27 13:42:52,773 - ERROR [kytos.core.controller] [app.py:1449:log_exception] (Thread-147) Exception on /api/kytos/core/auth/login [GET]
Traceback (most recent call last):
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.12/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.12/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.12/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.12/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/viniarck/repos/kytos/.direnv/python-3.9.12/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/viniarck/repos/kytos/kytos/core/auth.py", line 281, in _authenticate_user
    username = request.authorization["username"]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by viniarck** [comment]
@Alopalao, since you're already at it and almost done with the `epic_auth`, could you please also fix this one?
